"""add category thumbnail image table

Revision ID: 00406f512d51
Revises: 861d6bcb5d4d
Create Date: 2026-06-06 20:14:03.002570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '00406f512d51'
down_revision: Union[str, Sequence[str], None] = '861d6bcb5d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_thumbnail_image_data',
    sa.Column('filepath', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=False),
    sa.Column('id_', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category_data.id_'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user_data.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_category_thumbnail_image_data_category_id'), 'category_thumbnail_image_data', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_thumbnail_image_data_category_id'), table_name='category_thumbnail_image_data')
    op.drop_table('category_thumbnail_image_data')
    # ### end Alembic commands ###
