"""added new product_image storing table

Revision ID: 06c0e72e4a89
Revises: 97a79ce83623
Create Date: 2026-05-14 06:18:29.085130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '06c0e72e4a89'
down_revision: Union[str, Sequence[str], None] = '97a79ce83623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_image_data',
    sa.Column('id_', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user_data.id_'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_data.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_image_data')
    # ### end Alembic commands ###
