"""for product table there will be user_obj to konw who created this

Revision ID: 0a56a4bf2cac
Revises: 9221cdf47458
Create Date: 2026-05-22 09:40:45.650196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a56a4bf2cac'
down_revision: Union[str, Sequence[str], None] = '9221cdf47458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_data', sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_product_data_creator_id'), 'product_data', ['creator_id'], unique=False)
    op.create_foreign_key(None, 'product_data', 'user_data', ['creator_id'], ['id_'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_data', type_='foreignkey')
    op.drop_index(op.f('ix_product_data_creator_id'), table_name='product_data')
    op.drop_column('product_data', 'creator_id')
    # ### end Alembic commands ###
