"""category table's name column got now null value and unique

Revision ID: 2d548c5344e6
Revises: 31cd3621f119
Create Date: 2026-05-16 14:17:37.646581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d548c5344e6'
down_revision: Union[str, Sequence[str], None] = '31cd3621f119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_data', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_category_data_name'), table_name='category_data')
    op.create_index(op.f('ix_category_data_name'), 'category_data', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_data_name'), table_name='category_data')
    op.create_index(op.f('ix_category_data_name'), 'category_data', ['name'], unique=False)
    op.alter_column('category_data', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
