"""category now has self-reference relationship and add thigns and change some relation in other tables

Revision ID: 31cd3621f119
Revises: 06c0e72e4a89
Create Date: 2026-05-15 23:44:51.742534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31cd3621f119'
down_revision: Union[str, Sequence[str], None] = '06c0e72e4a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_data', sa.Column('icon_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('category_data', sa.Column('private_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('category_data', sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'category_data', 'category_data', ['parent_id'], ['id_'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category_data', type_='foreignkey')
    op.drop_column('category_data', 'parent_id')
    op.drop_column('category_data', 'private_note')
    op.drop_column('category_data', 'icon_name')
    # ### end Alembic commands ###
