"""add private_note in the product table

Revision ID: 3535d164a32b
Revises: 60a378b4fa09
Create Date: 2026-06-07 09:44:14.405217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3535d164a32b'
down_revision: Union[str, Sequence[str], None] = '60a378b4fa09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_data', sa.Column('private_note', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_data', 'private_note')
    # ### end Alembic commands ###
