"""brand table has added with link with product so that i can check what what items a brand has in my db

Revision ID: 53920a823d7f
Revises: ced7f6ce77ef
Create Date: 2026-05-16 23:10:21.084068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '53920a823d7f'
down_revision: Union[str, Sequence[str], None] = 'ced7f6ce77ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_data',
    sa.Column('id_', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_brand_data_name'), 'brand_data', ['name'], unique=True)
    op.add_column('product_data', sa.Column('brand_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'product_data', 'brand_data', ['brand_id'], ['id_'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_data', type_='foreignkey')
    op.drop_column('product_data', 'brand_id')
    op.drop_index(op.f('ix_brand_data_name'), table_name='brand_data')
    op.drop_table('brand_data')
    # ### end Alembic commands ###
