"""user table now has phone number, email and username as unique

Revision ID: 599b97a323de
Revises: 5f3bbe5cf31c
Create Date: 2026-05-07 18:28:10.800475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '599b97a323de'
down_revision: Union[str, Sequence[str], None] = '5f3bbe5cf31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_data', ['username'])
    op.create_unique_constraint(None, 'user_data', ['phone_no'])
    op.create_unique_constraint(None, 'user_data', ['email_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_data', type_='unique')
    op.drop_constraint(None, 'user_data', type_='unique')
    op.drop_constraint(None, 'user_data', type_='unique')
    # ### end Alembic commands ###
