"""make the user model class little design good

Revision ID: 5f3bbe5cf31c
Revises: e1f209f09508
Create Date: 2026-05-07 10:01:36.237933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5f3bbe5cf31c'
down_revision: Union[str, Sequence[str], None] = 'e1f209f09508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_data', 'phone_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_data', 'phone_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
