"""add brand thumbnail image storing informaiotn in a table

Revision ID: 60a378b4fa09
Revises: 00406f512d51
Create Date: 2026-06-06 20:28:46.345095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60a378b4fa09'
down_revision: Union[str, Sequence[str], None] = '00406f512d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_thumbnail_image_data',
    sa.Column('filepath', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=False),
    sa.Column('id_', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_data.id_'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user_data.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_brand_thumbnail_image_data_brand_id'), 'brand_thumbnail_image_data', ['brand_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_thumbnail_image_data_brand_id'), table_name='brand_thumbnail_image_data')
    op.drop_table('brand_thumbnail_image_data')
    # ### end Alembic commands ###
