"""Product thumbnail Image Model new table has added

Revision ID: 64448deed54e
Revises: bb0b3593b301
Create Date: 2026-05-19 18:31:32.790636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '64448deed54e'
down_revision: Union[str, Sequence[str], None] = 'bb0b3593b301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_thumbnail_image_data',
    sa.Column('id_', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filepath', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user_data.id_'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_data.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_product_thumbnail_image_data_product_id'), 'product_thumbnail_image_data', ['product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_thumbnail_image_data_product_id'), table_name='product_thumbnail_image_data')
    op.drop_table('product_thumbnail_image_data')
    # ### end Alembic commands ###
