"""added description on user role and some changes after change int DDD

Revision ID: 861d6bcb5d4d
Revises: 0a56a4bf2cac
Create Date: 2026-06-06 15:11:30.986293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '861d6bcb5d4d'
down_revision: Union[str, Sequence[str], None] = '0a56a4bf2cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role_data', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True))
    op.alter_column('user_role_data', 'id_',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_role_data', 'id_',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('user_role_data', 'description')
    # ### end Alembic commands ###
