"""is primary column has been deleted

Revision ID: a47d677a8651
Revises: e1a50909988e
Create Date: 2026-05-19 16:55:16.379449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a47d677a8651'
down_revision: Union[str, Sequence[str], None] = 'e1a50909988e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_image_data', 'is_primary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_image_data', sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
