"""productgalleryimage this new table has established by remove old one

Revision ID: bb0b3593b301
Revises: a47d677a8651
Create Date: 2026-05-19 18:04:34.127640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb0b3593b301'
down_revision: Union[str, Sequence[str], None] = 'a47d677a8651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_gallery_image_data',
    sa.Column('id_', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filepath', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user_data.id_'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_data.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_product_gallery_image_data_product_id'), 'product_gallery_image_data', ['product_id'], unique=False)
    op.drop_table('product_image_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_image_data',
    sa.Column('id_', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filepath', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alt_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('external_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user_data.id_'], name=op.f('product_image_data_creator_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['product_data.id_'], name=op.f('product_image_data_product_id_fkey')),
    sa.PrimaryKeyConstraint('id_', name=op.f('product_image_data_pkey'))
    )
    op.drop_index(op.f('ix_product_gallery_image_data_product_id'), table_name='product_gallery_image_data')
    op.drop_table('product_gallery_image_data')
    # ### end Alembic commands ###
