"""hsn_no column has been added to the product table

Revision ID: ced7f6ce77ef
Revises: 2d548c5344e6
Create Date: 2026-05-16 22:01:09.227304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ced7f6ce77ef'
down_revision: Union[str, Sequence[str], None] = '2d548c5344e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_data', sa.Column('hsn_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_data', 'hsn_no')
    # ### end Alembic commands ###
