"""rename filename to filepath

Revision ID: e1a50909988e
Revises: 53920a823d7f
Create Date: 2026-05-18 15:03:13.595469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "e1a50909988e"
down_revision: Union[str, Sequence[str], None] = "53920a823d7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('product_image_data', sa.Column('filepath', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # op.drop_column('product_image_data', 'filename')
    # ### end Alembic commands ###
    op.alter_column(
        table_name="product_image_data",
        column_name="filename",
        new_column_name="filepath",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column(
    #     "product_image_data",
    #     sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=True),
    # )
    # op.drop_column("product_image_data", "filepath")
    # ### end Alembic commands ###

    op.alter_column(
        table_name="product_image_data",
        column_name="filepath",
        new_column_name="filename",
    )