"""add the password_hashed in the user table so that i can check the password of user

Revision ID: e1f209f09508
Revises: 7321e93d3d31
Create Date: 2026-05-06 18:39:01.991507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e1f209f09508'
down_revision: Union[str, Sequence[str], None] = '7321e93d3d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('password_hashed', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'password_hashed')
    # ### end Alembic commands ###
